base_domain             = "moyinopoolas.com"
aws_region              = "us-east-1"
tag_env                 = "prod"
id_rsa                  = ""
registrationToken       = ""
ci_project_repo         = "Moyinoo/K8s-CI"
cd_project_repo         = "Moyinoo/K8s-CD"
