base_domain             = "moyinopoolas.com"
aws_region              = "us-east-1"
tag_env                 = "prod"
id_rsa                  = "${{ secrets.EC2_KEY_PAIR }}"
registrationToken       = "${{ secrets.API_TOKEN_GITHUB }}"
ci_project_repo         = "K8s-CI"
cd_project_repo         = "K8s-CD"
